# Generated by Django 4.1.4 on 2022-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="shares",
            field=models.IntegerField(default=0, verbose_name="number of shares"),
        ),
    ]
